name: Update PlantUML Jar

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run update script
        id: update_script
        run: python scripts/update_plantuml.py
      - name: Add new jar to git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add third_party/*.jar
          git add plantumlwebview.ini
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update PlantUML to latest version
          title: 'Update PlantUML to latest version'
          body: |
            This PR updates the PlantUML MIT-licensed jar to the latest version.
            This was done automatically by the update-plantuml workflow.
          branch: update-plantuml
          base: main
      - name: Enable Automerge
        if: steps.cpr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
      - name: Check outputs
        if: steps.cpr.outputs.pull-request-number
        run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
